version: '3.8'

services:
  #контейнеры frontend'a
  nginx:
    container_name: frontend_nginx
    image: "nginx:stable-alpine"
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf/:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    networks:
      - frontend

  nodejs:
    container_name: nodejs
    environment:
      - PORT=5173
    build:
      context: dockerfiles
      dockerfile: nodejs.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/laravel
    networks:
      - frontend

  # контейнеры backend'a
  php:
    container_name: frontend_php
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - backend
      - frontend

  redis:
    container_name: frontend_redis
    image: redis/redis-stack:latest
    # network_mode: "host"
    # ports:
    #   - 6379:6379
    #   - 8001:8001
    networks:
      - frontend

  mysql:
    container_name: frontend_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - frontend

  phpmyadmin:
    container_name: frontend_pma
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_PORT: 3306
    networks:
      - frontend

  reverb:
    container_name: frontend_reverb
    environment:
      - PORT=9000
    build:
      context: dockerfiles
      dockerfile: reverb.Dockerfile
    depends_on:
      - mysql
      - nodejs
      - php
    volumes:
      - ./src:/var/www/laravel
    healthcheck:
      test: [ "CMD", "php", "artisan", "migrate" ]
      interval: 300s
      timeout: 400s
      retries: 10
    ports:
      - 9000:9000
    networks:
      - frontend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.4
    ports:
    #   - 15672:15672
      - 5672:5672
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    networks:
      - frontend

  supervisor:
    build:
      context: dockerfiles
      dockerfile: supervisor.Dockerfile
    container_name: frontend_supervisor
    volumes:
      - ./src:/var/www/laravel
      - ./configs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./src/storage/logs:/etc/supervisor/logs
    command: "supervisord -n -c /etc/supervisord.conf"
    ports:
      - 6002:6001
    networks:
      - backend

  # вспомогательные контейнеры
  composer:
    container_name: frontend_composer
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - frontend

  artisan:
    container_name: frontend_artisan
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
    networks:
      - frontend

networks:
  backend:
    driver: bridge
    external: true
  frontend:
    driver: bridge
  frontend_nginx:
    driver: bridge
