version: '3.8'
services:

  # PHP Service
  app:
    image: 3ddi3/test
    volumes:
      - ./configs/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./src:/var/www/laravel
    working_dir: /var/www/laravel
    networks:
      - app-network

  # php:
  #   container_name: php
  #   build:
  #     context: dockerfiles
  #     dockerfile: php.Dockerfile
  #   networks:
  #     - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "4443:443"
    volumes:
      - ./src:/var/www/laravel
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:5.7.22
    volumes:
      - ./data/mysql:/var/lib/mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
